import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Providers from "@/components/providers/SessionProvider";
import SpaceBackground from "@/components/ui/SpaceBackground";
import { TutorialProvider } from "@/components/tutorial/TutorialContext";
import TutorialOverlay from "@/components/tutorial/TutorialOverlay";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <TutorialProvider>
            <SpaceBackground>
              <TutorialOverlay />
              {children}
            </SpaceBackground>
          </TutorialProvider>
        </Providers>
      </body>
    </html>
  );
}
